export const vinylTapAbi = [
  {
    type: "function",
    name: "userBeats",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userBasses",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userEchoes",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalBeats",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalBasses",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalEchoes",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "tapBeat",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "tapBass",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "tapEcho",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "BeatTapped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userBeats", type: "uint256", indexed: false },
      { name: "totalBeats", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BassTapped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userBasses", type: "uint256", indexed: false },
      { name: "totalBasses", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EchoTapped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userEchoes", type: "uint256", indexed: false },
      { name: "totalEchoes", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
